### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by m3ngyang** [baidu/cloud-provider-baiducloud#19]
Prerequisites before contributing to sig
- [ ] Add CONTRIBUTING.md
- [ ] Establish OWNERS and OWNER_ALIASES files
- [ ] Add SECURITY_CONTACTS file
- [ ] Add copyright boiler plate header to all files
- [ ] Add script to verify boilerplate header
- [ ] License Auditing
- [ ] Creating an issue on kubernetes/org (kubernetes/org#196)
- [ ] Enabling the Circle CI status contexts as required in kubernetes/test-infra (kubernetes/test-infra#9938)
- [ ] Update prow/config.yaml in kubernetes/test-infra to set merge method (kubernetes/test-infra#9938)
- [ ] Disable integration with Kubermatic internal Prow
- [ ] Ensure relevant webhooks are enabled.
  - [ ] cncf-cla webhook
  - [ ] prow's webhook
- [ ] Update CONTRIBUTING.md to mention Kubernetes slack channels.
- [ ] Find how to correctly handle Docker images
- [ ] Update README and docs to use new repository URL
- [x] Update Go import paths to `sigs.k8s.io/cluster-api-provider-baiducloud/...`
- [ ] Update sigs.yaml file in kubernetes/community (kubernetes/community#2864)
