### ISSUE TITLE
CCM 2019-Q2

### ISSUE THREAD

**Issue by hello2mao** [baidu/cloud-provider-baiducloud#39]
**Feature List:**
- [x] Support Service EIP config by annotation #40 
- [x] Support Service BLB using UDP Listener #41 
- [ ] Support Service BLB using HTTP Listener #42 
- [ ] Support Service BLB using HTTPS Listener #43

**Bug List:**
- [ ] NodeAddressesByProviderID unimplemented #23 
- [ ] InstanceExistsByProviderID unimplemented #24 
- [ ] InstanceShutdownByProviderID unimplemented #25
- [ ] ensure route after delete from VPV console by mistake #31
- [ ] delete blb and eip when change service type from LoadBalancer to other #36
